[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "snub-yeah", email = "snublol@proton.me" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
api = "api:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
